### ISSUE TITLE
not working for #rere.cm@ebc.com

### ISSUE THREAD

**Issue by mohantyt** [mailgun/validator-demo#12]
not working for "#rere.cm@ebc.com"

please check and correct it

**Comment by msigley** [comment]
@mohantyt: "#rere.cm@ebc.com" verifies in the current implementation in my tests. Can you provide steps to reproduce? Maybe what web browser/OS you are testing in?

**Comment by mohantyt** [comment]
Open below mentioned link and validate "#rere.cm@ebc.com"
http://mailgun.github.io/validator-demo/

**Comment by msigley** [comment]
That address is valid according to the email address standard outlined in the link below and that is what I see when I attempt to validate it.

https://en.m.wikipedia.org/wiki/Email_address

-----Original Message-----

**Comment by mohantyt** [comment]
Sorry for the wrong request of valid email address.

You are absolutely correct.
Thanks
